# Generated by Django 3.0.7 on 2020-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='e_tin',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nid',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Others', 'Others')], max_length=45),
        ),
    ]
