# Generated by Django 3.0.7 on 2021-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210519_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=200579, unique=True),
        ),
    ]
